"""add_is_active_to_resumes

Revision ID: 4a63deeeb3d7
Revises: 
Create Date: 2026-08-10 13:58:03.242774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a63deeeb3d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index('ix_single_active_resume', 'resumes', ['user_id'], unique=True, sqlite_where=sa.text('is_active = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_single_active_resume', table_name='resumes', sqlite_where=sa.text('is_active = 1'))
    op.drop_column('resumes', 'is_active')
    # ### end Alembic commands ###
